### ISSUE TITLE
BILL_EMAILS config is ignored

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico-billing#23]
The BILL_EMAILS setting is not used anywhere. I would remove it

Note: The main Juntagrico app will remove the EMAILS setting in release 2.0.0.
Instead all templates will be [namespaced](https://docs.djangoproject.com/en/4.1/intro/tutorial03/#write-views-that-actually-do-something) and overriding can happen with the method described here:
https://docs.djangoproject.com/en/4.0/howto/overriding-templates/

As this overriding already works at the moment, I would rather document that, instead of fixing the BILL_EMAILS setting.

**Comment by samuel-iseli** [comment]
don't really know where BILL_EMAILS comes from, never used it in the billing project.
Will remove it.

**Comment by samuel-iseli** [comment]
Yes we should remove this setting.
Is already part of issue #7 . 
Closing this issue as duplicate
