### ISSUE TITLE
Display reference number in notification email

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico-billing#24]
For those paying by IBAN directly the reference number should be printed on the notification email as well:
https://github.com/juntagrico/juntagrico-billing/blob/056551cb6eaf27f6c929b3a7e07f5da81434973e/juntagrico_billing/templates/mails/bill_notification.txt#L20-L24

See my patch for reference.
https://github.com/Huebhof/Juntagrico/blob/2a2271a312ef3623c2c27946962de79f004a4c6c/huebhof/apps.py#L36-L40

**Comment by samuel-iseli** [comment]
Added `Bill.refnumber` property and show it in notification mail if IBAN is a QR IBAN. 
The refnumber is shown as single 27 char string, not segmented like in example of @pascalfree .
I think that's OK as it will be mainly used by copy/paste.
