### ISSUE TITLE
Error message: Payment file could not be read element Refs/Instlrd not found.

### ISSUE THREAD

**Issue by ringloop2** [juntagrico/juntagrico-billing#27]
When importing the payment file in camt.054 format, I get an error message.

**Comment by samuel-iseli** [comment]
Can you send me the failing payments file by e-mail?
You are probably the first one really using the payment import feature. I implemented it some years ago but unfortunately it never went into production.

**Comment by samuel-iseli** [comment]
Identified the problem:
we need a unique ID for each payment detail, to prevent duplicate imports.
based on the camt files from postfinance the `Refs/InstrId` seemed suitable for this.

Unfortunately this seems not to be so well standardized (or I don't understand it really...). Anyway the camt File that causes the error doesn't have this element in its `Refs` element. But it has a `Refs/TxId` element that seems to unique (hopefully) too.

I'll change the payment_reader to use the `TxId` if the `InstrId` isn't found.

**Comment by ringloop2** [comment]
In this paper from SIX you will find information about the standards of the XML file (camt.054). 
![image](https://user-images.githubusercontent.com/106236761/220549707-ee2c675a-ddf4-4bc5-a1c7-32d31d15d74a.png)
[business-rules-sps-2022-de.pdf](https://github.com/juntagrico/juntagrico-billing/files/10801022/business-rules-sps-2022-de.pdf)

**Comment by samuel-iseli** [comment]
I don't find these documents particularly instructive...
@ringloop2: where did you get the screenshot describing the references from? Didn't find this info in the attached document.

Anyway I will try to use `TxId` as unique reference to decide if a payment has already been processed.
