### ISSUE TITLE
Setting to disable user bills view

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico-billing#3]
it should be possible to toggle the user bill view so that one can use the bookkeeping toll wihtout exposing the bills to the user

**Comment by samuel-iseli** [comment]
Implemented by linking the already existing "BILLING" setting (see juntagrico.config) to the billing_user_menu template.

**Comment by motu55** [comment]
move the billing setting into this extension since it is dead code there. Also the setting should be more meaningfull since the billing setting was an all or nothing setting

**Comment by samuel-iseli** [comment]
Would you extend the `config` template-tag in juntagrico to support per app registered config classes?
Or should I implement a specific `billing-config` template-tag for use in the menu template? this would be possible without changes in juntagrico

**Comment by samuel-iseli** [comment]
Decided to extend the `config` template-tag and add the possibility for addon apps to register their own `Config` classes.
Changed the existing properties on the juntagrico_billing `Config` class to use the mechanisms provided by `juntagrico.config`.
