### ISSUE TITLE
Reference to invalid field organisation_bank_connection.ESR

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico-billing#7]
`organisation_bank_connection.ESR` is not part of juntagrico's default setup. Shouldn't the IBAN be used here?

https://github.com/juntagrico/juntagrico-billing/blob/44cc98159199c1c2c278f6246d6fed7c652c6ee2/juntagrico_billing/templates/mails/bill_share.txt#L16

**Comment by samuel-iseli** [comment]
We have the newly introduced concept of payment-types now in juntagrico_billling. 
There are multiple payment types and one of them is referenced as default paymenttype by a reference from the singleton Settings object. The mail-template bill_notification.txt is using this. Other places displaying an account for payment should be changed to using paymenttype too.

**Comment by samuel-iseli** [comment]
I don't know much about shares billing. @motu55, is this actively used or can it be removed?

**Comment by samuel-iseli** [comment]
As far as I can see, the email templates `bill_share.txt, bill_sub.txt and bill_extra.extrasub.txt` are not used anywhere.
* We should remove these templates and the corresponding references in `juntagrico_billing.config`.
* Same for the `Config.esr` setting in `juntagrico_billing.config`
* Remove description for these settings from `settings.rst` file in `juntagrico-billing`
